### ISSUE TITLE
💭 Adjusting the "Full Database Spreadsheet" button link

### ISSUE THREAD

**Issue by JamesAlfonse** [WhyDRS/website#16]
I was visiting [this page](https://www.whydrs.org/database) and noticed it was linking to whydrsdatabase.on.fleek.co
For consistency, I think it should link to database.whydrs.org. @JFWooten4 @tehchives 

![Screenshot 2024-10-25 at 2 23 34 AM](https://github.com/user-attachments/assets/ae62aad9-dabf-42fa-91f4-34e9299b36f8)

**Comment by JFWooten4** [comment]
Thanks for the catch @JamesAlfonse and fast fix @tehchives 💜🙌🚀
